version: '3'

services:
  fpm:
    container_name: fpm
    build:
      context: .
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    container_name: webserver
    depends_on:
      - fpm
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public

  database:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '!ChangeMe!'
      MYSQL_ROOT_PASSWORD: '!ChangeMe!'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
###> doctrine/doctrine-bundle ###
  db:
###< doctrine/doctrine-bundle ###
