version: '3'

services:
###> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - "3000:3000"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    container_name: mail
    ports: ["1025", "1080"]
###< symfony/mailer ###
