services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\EventListener\IExceptionListener:
        class: App\EventListener\DetailExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Behatch\HttpCall\Request: ~