parameters:

services:
    # Event Listener Services
    # DomainException Listener
  App\EventListener\IExceptionListener:
    class: App\EventListener\DevExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
